"$schema" = "https://schema.tauri.app/config/2"
productName = "easy-todo"
version = "0.1.0"
identifier = "com.zero.easy-todo"

### 打包配置
[build]
# 前端静态资源目录
frontendDist = "../dist"

# 前端开发服务器
devUrl = "http://localhost:5173"
beforeDevCommand = "pnpm dev"
beforeBuildCommand = "pnpm build"

### 应用配置
[[app.windows]]
  # 窗口标题
  title = "easy-todo"
  # 窗口初始大小
  width = 1000
  height = 800
  # 是否可拖拽调整窗口大小, 默认为 true
  resizable = true
  # 是否显示标题栏, 默认为 true
  decorations = true
  # 是否全屏显示, 全屏时会隐藏标题栏和边框
  fullscreen = false
  # 是否可见, 默认可见
  visible = true

  ### 窗口配置


[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
